### ISSUE TITLE
Implementing mock_api for unit tests

### ISSUE THREAD

**Issue by mel-liow** [UBC-MDS/rpollution#14]
@christopheralex  @danfke 
Quick tutorial on how to mock the api in unit tests:
I followed this library: https://cran.r-project.org/web/packages/httptest/vignettes/httptest.html

1. make sure `library(httptest)` is imported in the test file
2. use `with_mock_api({ })` wrapper function around all of the `testthat` tests
3. when calling the api with your tests you will first get an error that looks like: 
<img width="788" alt="Screenshot 2022-01-24 at 20 53 01" src="https://user-images.githubusercontent.com/40150248/150913233-5598a848-7424-433f-924e-0706f9f1b37d.png">

```
.....end=1606747870&appid=error_api_key (api.openweathermap.org/data/2.5/air_pollution/history-a7cfa8.json
```
The last line (pink text) is the file path where it expects to find a file called `history-a7cfa8.json`. 
4. you need to create this file and add your mock data to it
5. run the function again with the same arguments and it should print out whatever data you have in the .json file.
6. NOTE: every time you change the arguments in the test fn, it will throw the above error with a different json file name 😒, so just make sure you rename the mock data file. 
7. ALSO: when adding the .json file, make sure there aren't any leading commas because R doesn't like it 

Let me know if you have any questions! I realise this is a lot of effort and out of the course scope so will help set this up if you need!

**Comment by christopheralex** [comment]
A quick query - If the file name changes for argument change in test fn . How do we automate this in CI pipeline through github actions ?

**Comment by mel-liow** [comment]
Ah no, it shouldn't affect the CI pipeline, sorry let me clarify.
If you change the arguments of your function that you call in a test (because you made a typo or a mistake) after setting up your .json with mock data, it might look for data in a different .json file that you've not created (it will throw the pink error message again with a different file suffix). e.g. rather than `history-a7cfa8.json` it will ask for `history-xxxxxx.json`.
So this is just a precaution if this happens to you^. 

Our tests shouldn't change so i think it's ok - just an annoying thing to note if you're playing around with the arguments.

**Comment by christopheralex** [comment]
Thanks Mel for the detailed explanation 👍
